---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Рок-гурт
description: У цьому проекті ви дізнаєтеся, як запрограмувати власні музичні інструменти!
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Рок-гурт
  - 
    title: Спрайт
  - 
    title: Сцена
  - 
    title: Виготовлення барабана
  - 
    title: "Завдання: покращити свій барабан"
    challenge: true
  - 
    title: Створення співака
  - 
    title: Костюми
  - 
    title: "Завдання: покращити групу"
    challenge: true
  - 
    title: "Що далі?"
