---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Рок-гурт
description: У цьому проекті ви дізнаєтеся, як запрограмувати власні музичні інструменти!
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: З днем народження
  - 
    title: Спрайти
  - 
    title: Сцена
  - 
    title: Робимо барабан
  - 
    title: "Завдання: вдоскональте свій барабан"
    challenge: true
  - 
    title: Робимо співачку
  - 
    title: Костюми
  - 
    title: "Завдання: покращити групу"
    challenge: true
  - 
    title: "Що далі?"
