title: Rock Band
hero_image: images/banner.png
subtitle: rock-band subtitle
description: Learn how to code your own musical instruments!
published: true

steps:
  - title: Introduction
    duration: 10
