title: Rock band
hero_image: images/hero-rock-band-large.png
subtitle: Bang those drums...
description: Learn how to code your own musical instruments!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
published: true
steps:
  - title: Introduction
    duration: 10
  - title: 'Step 1: Sprites'
    duration: 10
  - title: 'Step 2: The Stage'
    duration: 10
  - title: 'Step 3: Making a Drum'
    duration: 10
  - title: 'Challenge: Improving your drum'
    duration: 10
  - title: 'Step 4: Making a Singer'
    duration: 10
  - title: 'Step 5: Costumes'
    duration: 10
  - title: "Challenge: Changing your drum's costume"
    duration: 10
  - title: 'Challenge: Make your own band'
    duration: 10
