title: Rock Band
hero_image: images/banner.png
subtitle: Not sure one is needed.
description: Learn how to code your own musical instrument!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band?redirect=false
theme: cc-prototype
published: true
steps:
  - title: Introduction
    duration: 10
