title: rock-band
hero_image: images/banner.png
subtitle: rock-band subtitle
description: rock-band description
published: true

steps:
  - title: Introduction
    duration: 10
  - title: What you'll need
    duration: 10
