title: Rock Band
hero_image: images/hero-rock-band-large.png
subtitle: Bang those drums...
description: Learn how to code your own musical instruments!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band?redirect=false
theme: red
listed: true
ingredient: false
duration: 2
steps:
  - title: Introduction
  - title: 'Step 1: Sprites'
  - title: 'Step 2: The Stage'
  - title: 'Step 3: Making a Drum'
  - title: 'Challenge: Improving your drum'
  - title: 'Step 4: Making a Singer'
  - title: 'Step 5: Costumes'
  - title: "Challenge: Changing your drum's costume"
  - title: 'Challenge: Make your own band'
