title: rock-band
hero_image: images/banner.png
subtitle: rock-band subtitle
description: rock-band description
published: false

steps:
  - title: Introduction
    duration: 10
  - title: Sprites
    duration: 10
  - title: The Stage
    duration: 10
  - title: Making a Drum
    duration: 10
  - title: Costumes
    duration: 10
