---
hero_image: images / hero-rock-band-large.png
theme: लाल
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, डिझाइन -1, प्रोग्रामिंग -1, फेज- comp-0, उत्पादन 0, समुदाय-0
title: रॉक बँड
description: 'आपल्या स्वत: च्या वाद्य वाजवा कसे शिका'
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: सुरवातीपासून
site_areas: प्रकल्प
hardware: ''
software: सुरवातीपासून
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: परिचय
  - 
    title: आपल्याला कशाची आवश्यकता लागेल
  - 
    title: Sprites
  - 
    title: स्टेज
  - 
    title: ड्रम बनवा
  - 
    title: "आव्हान: आपले ड्रम सुधारित करा"
  - 
    title: एक गायक बनविणे
  - 
    title: पोशाख
  - 
    title: "आव्हान: आपल्या ड्रमचे पोशाख बदला"
  - 
    title: "आव्हान: आपल्या स्वत: च्या बँड करा"
