---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: ロックバンド
description: このプロジェクトではプログラミングを使った楽器の作り方を学びます！
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: 前書き
  - 
    title: スプライト
  - 
    title: ステージ
  - 
    title: ドラムを作ろう
  - 
    title: "チャレンジ：ドラムの改良（かいりょう）"
    challenge: true
  - 
    title: 歌手を作ろう
  - 
    title: コスチューム
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "次は何をしますか？"
