---
hero_image: images / hero-rock-band-large.png
listed: true
copyedit: false
title: Ban nhạc rock
description: Tìm hiểu cách mã hóa nhạc cụ của riêng bạn
version: 4.1.0
last_tested: 2018-10-12
steps:
  - 
    title: Giới thiệu
  - 
    title: Sprites
  - 
    title: The Stage
  - 
    title: Making a drum
  - 
    title: "Challenge: improve your drum"
    challenge: true
  - 
    title: Making a singer
  - 
    title: Costumes
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "What next?"
