---
hero_image: images / hero-rock-band-large.png
listed: true
copyedit: false
title: Ban nhạc rock
description: Tìm hiểu cách mã hóa nhạc cụ của riêng bạn
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Giới thiệu
  - 
    title: Sprites
  - 
    title: Sân khấu
  - 
    title: Làm trống
  - 
    title: "Thử thách: cải thiện trống của bạn"
    challenge: true
  - 
    title: Làm ca sĩ
  - 
    title: Trang phục
  - 
    title: "Thử thách: cải thiện ban nhạc của bạn"
    challenge: true
  - 
    title: "Tiếp theo là gì?"
