---
hero_image: images / hero-rock-band-large.png
theme: đỏ
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, thiết kế-0, lập trình-1, phys-comp-0, sản xuất-0, cộng đồng-0
title: Ban nhạc rock
description: Tìm hiểu cách mã hóa nhạc cụ của riêng bạn
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: vết trầy
site_areas: dự án
hardware: ''
software: vết trầy
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Sprites
  - 
    title: Sân khấu
  - 
    title: Làm trống
  - 
    title: "Thách thức: cải thiện trống của bạn"
  - 
    title: Làm ca sĩ
  - 
    title: Trang phục
  - 
    title: "Thách thức: thay đổi trang phục trống của bạn"
  - 
    title: "Thách thức: tạo thành ban nhạc của riêng bạn"
