---
hero_image: images / qəhrəman-rock-band-large.png
theme: qırmızı
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rok qrupu
description: Öz musiqi alətlərini necə kodlaşdırdığınızı öyrənin
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: cızıq
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Giriş
  - 
    title: Nə lazımdır?
  - 
    title: Sprites
  - 
    title: Səhnə
  - 
    title: Bir baraban edilməsi
  - 
    title: "Challenge: barabanınızı artırın"
  - 
    title: Bir müğənninin edilməsi
  - 
    title: Geyimlər
  - 
    title: "Çağırış: nağara kostyumu dəyişdirin"
  - 
    title: "Çağırış: öz bandını yaradın"
