---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rockband
description: I dette projekt skal du lære, hvordan du kan kode dit eget musikinstrument!
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Rockband
  - 
    title: Sprites
  - 
    title: The Stage
  - 
    title: Making a drum
  - 
    title: "Challenge: improve your drum"
    challenge: true
  - 
    title: Making a singer
  - 
    title: Costumes
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "What next?"
