---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock bend
description: U ovom projektu naučit ćeš kako programirati vlastite glazbene instrumente!
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Sretan rođendan
  - 
    title: Likovi
  - 
    title: Pozornica
  - 
    title: Napravi bubanj
  - 
    title: "Izazov: Poboljšaj svoj bubanj"
    challenge: true
  - 
    title: Dodaj pjevača ili pjevačicu
  - 
    title: Kostimi
  - 
    title: "Izazov: Poboljšaj svoj bend"
    challenge: true
  - 
    title: "Što dalje?"
