---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock bend
description: U ovom projektu naučit ćeš kako programirati vlastite glazbene instrumente!
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Sretan rođendan
  - 
    title: Sprites
  - 
    title: The Stage
  - 
    title: Making a drum
  - 
    title: "Challenge: improve your drum"
    challenge: true
  - 
    title: Making a singer
  - 
    title: Costumes
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "What next?"
