hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Banda de Rock
description: ¡Aprende a codificar tus propios instrumentos musicales!
original_url: https://projects.raspberrypi.org/en/projects/rock-band
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Objetos
- title: El Escenario
- title: Crear un tambor
- title: "Desafío: Mejorar tu tambor"
- title: Crear un cantante
- title: "Desafío: Cambiar el disfraz de tu cantante"
- title: "Desafío: Crear tu propia banda"
