hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Banda de Rock
description: ¡Aprende a codificar tus propios instrumentos musicales!
original_url: https://projects.raspberrypi.org/en/projects/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps: 
- title: Introducción
- title: Objetos
- title: El Escenario
- title: Crear un tambor
- title: "Desafío: Mejorar tu tambor"
- title: Crear un cantante
- title: "Desafío: Cambiar el disfraz de tu cantante"
- title: "Desafío: Crear tu propia banda"