---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Band Roc
description: Dysga sut i godio dy offerynnau cerddorol dy hunan!
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Cipluniau
  - 
    title: Llwyfan
  - 
    title: Gwneud Drwm
  - 
    title: "Her: Perffeithio dy ddrwm"
    challenge: true
  - 
    title: Gwneud Canwr
  - 
    title: Gwisgoedd
  - 
    title: "Her: Newid edrychiad dy ddrwm"
    challenge: true
  - 
    title: "Her: Gwneud band dy hunan"
