---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock-Band
description: Lerne deine eigenen Musikinstrumente zu programmieren
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Einleitung
  - 
    title: Figuren
  - 
    title: Die B체hne
  - 
    title: Eine Trommel machen
  - 
    title: "Herausforderung: Verbessere deine Trommel"
    challenge: true
  - 
    title: Einen S채nger machen
  - 
    title: Kost체me
  - 
    title: "Kost체me"
    challenge: true
  - 
    title: "Herausforderung: Noch mehr Hindernisse!"
