hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rock-Band
description: In diesem Projekt lernst du, wie du deine eigenen Musikinstrumente programmieren kannst!
original_url: https://projects.raspberrypi.org/en/projects/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps: 
- title: Einleitung
- title: Eine Trommel programmiere
- title: "Herausforderung: Deine Trommel verbessern"
- title: Eine Sängerin programmieren
- title: Ein Becken programmieren
- title: Hintergrundmusik
- title: "Herausforderung: Erstelle deine eigene Band"