---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: În acest proiect vei învăța să creezi propiul tău instrument muzical!
version: 4.1.0
last_tested: 2018-10-12
steps:
  - 
    title: Rock Band
  - 
    title: Sprites
  - 
    title: The Stage
  - 
    title: Making a drum
  - 
    title: "Challenge: improve your drum"
    challenge: true
  - 
    title: Making a singer
  - 
    title: Costumes
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "What next?"
