---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: Învață cu să creezi propriul tău instrument muzical
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Introducere
  - 
    title: Personaje
  - 
    title: Scena
  - 
    title: Creează toba
  - 
    title: "Challenge: improve your drum"
    challenge: true
  - 
    title: Creează o cântăreață
  - 
    title: Costume
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "Ce urmează?"
