---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Banda de Rock
description: Aprenda a programar os seus próprios instrumentos musicais
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Introdução
  - 
    title: Atores
  - 
    title: O palco
  - 
    title: Fazendo um tambor
  - 
    title: "Desafio: Melhore o seu tambor"
    challenge: true
  - 
    title: Fazendo um cantor
  - 
    title: Fantasias
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "E agora?"
