---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Band rock
description: Pelajari cara membuat kode alat musik Kamu sendiri
version: 4.1.1
last_tested: 10-12-2018
steps:
  - 
    title: Pengantar
  - 
    title: Gambar
  - 
    title: Panggung
  - 
    title: Membuat dram
  - 
    title: "Tantangan: tingkatkan band kamu"
    challenge: true
  - 
    title: Membuat penyanyi
  - 
    title: Kostum
  - 
    title: "Tantangan: tingkatkan band kamu"
    challenge: true
  - 
    title: "Apa selanjutnya?"
