---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock skupina
description: Naučite se programirati lastna glasbila
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Uvod
  - 
    title: Figure
  - 
    title: Oder
  - 
    title: Izdelava bobna
  - 
    title: "Izziv: izboljšajte svoj boben"
    challenge: true
  - 
    title: Ustvarjanje pevke
  - 
    title: Kostumi
  - 
    title: "Izziv: izboljšajte svoj band"
    challenge: true
  - 
    title: "Kaj je naslednje?"
