---
hero_image: slike / hero-rock-band-large.png
theme: rdeča
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rock skupina
description: Več o kodiranju lastnih glasbenih instrumentov
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: praska
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali
  - 
    title: Sprites
  - 
    title: Faza
  - 
    title: Izdelava bobna
  - 
    title: 'Izziv: izboljšajte svoj boben'
  - 
    title: Ustvarjanje pevca
  - 
    title: Kostumi
  - 
    title: 'Izziv: spremenite kostum bobna'
  - 
    title: 'Izziv: naredite svoj lastni bend'
