---
hero_image: slike / hero-rock-band-large.png
listed: true
copyedit: false
title: Rock skupina
description: Več o kodiranju lastnih glasbenih instrumentov
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Uvod
  - 
    title: Sprites
  - 
    title: Faza
  - 
    title: Izdelava bobna
  - 
    title: "Izziv: izboljšajte svoj boben"
    challenge: true
  - 
    title: Ustvarjanje pevke
  - 
    title: Kostumi
  - 
    title: "Izziv: izboljšajte svoj band"
    challenge: true
  - 
    title: "Kaj je naslednje?"
