---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rocková skupina
description: Nauč se, jak kódovat vlastní hudební nástroje
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Úvod
  - 
    title: Sprajty
  - 
    title: Jeviště
  - 
    title: Vytvoření bubnu
  - 
    title: "Výzva: vylepšení bubnu"
    challenge: true
  - 
    title: Přidání zpěvačky
  - 
    title: Kostýmy
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "Co dál?"
