---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Banda de Rock
description: '¡En este Proyecto aprenderás cómo codificar tus propios instrumentos musicales!'
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Banda de Rock
  - 
    title: Objetos
  - 
    title: El Escenario
  - 
    title: Haciendo un tambor
  - 
    title: "Desafío: mejora tu tambor"
    challenge: true
  - 
    title: Haciendo un cantante
  - 
    title: Disfraces
  - 
    title: "Challenge: mejora tu banda"
    challenge: true
  - 
    title: "¿Que sigue?"
