---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rokkbänd
description: Õpi, kuidas enda muusikariistu kodeerida
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Sissejuhatus
  - 
    title: Spraidid
  - 
    title: Lava
  - 
    title: Trummi tegemine
  - 
    title: "Väljakutse: täiusta oma trummi"
    challenge: true
  - 
    title: Laulja tegemine
  - 
    title: Kostüümid
  - 
    title: "Väljakutse: parandage oma bändi"
    challenge: true
  - 
    title: "Mis edasi?"
