---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Kapela rockowa
description: Wykonując ten projekt nauczysz się jak zaprogramować własne instrumenty muzyczne!
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Wprowadzenie
  - 
    title: Duszki
  - 
    title: Scena
  - 
    title: Tworzenie bębenka
  - 
    title: "Wyzwanie: popraw swój bębenek"
    challenge: true
  - 
    title: Dodawanie wokalistki
  - 
    title: Kostiumy
  - 
    title: "Challenge: improve your band"
    challenge: true
  - 
    title: "Co następne?"
