---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rockband
description: Lär dig hur du kodar dina egna musikinstrument
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Introduktion
  - 
    title: Sprites
  - 
    title: Scenen
  - 
    title: Att göra en trumma
  - 
    title: "Utmaning: förbättra din trumma"
    challenge: true
  - 
    title: Skapa en sångare
  - 
    title: Klädsel
  - 
    title: "Utmaning: förbättra ditt band"
    challenge: true
  - 
    title: "Vad händer nu?"
