---
hero_image: imej / hero-rock-band-large.png
theme: merah
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, reka bentuk-0, pengaturcaraan-1, phys-comp-0, pembuatan-0, komuniti-0
title: Kumpulan rock
description: Ketahui cara mengodkan alat muzik anda sendiri
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: awal
site_areas: projek
hardware: ''
software: awal
version: 4
last_tested: 2017-10-01
steps:
  - 
    title: Pengenalan
  - 
    title: Apa yang anda perlukan
  - 
    title: Sprites
  - 
    title: Pentas
  - 
    title: Membuat gendang
  - 
    title: "Cabaran: memperbaiki drum anda"
  - 
    title: Membuat penyanyi
  - 
    title: Kostum
  - 
    title: "Cabaran: tukar kostum dram anda"
  - 
    title: "Cabaran: buat band sendiri"
