---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rok grupa
description: Nauči kako da programiraš sopstvene muzičke instrumente
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Uvod
  - 
    title: Likovi (sprites)
  - 
    title: Pozornica (stage)
  - 
    title: Pravljenje bubnja
  - 
    title: "Izazov: poboljšaj svoj bubanj"
    challenge: true
  - 
    title: Stvaranje pjevačice
  - 
    title: Kostimi (costumes)
  - 
    title: "Kostimi (costumes)"
    challenge: true
  - 
    title: "Izazov: više prepreka!"
