---
hero_image: imagess/hero-rock-band-large.png
theme: rouge
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Groupe de rock
description: Apprends à programmer tes propres instruments de musique
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projets
hardware: ''
software: scratch
version: 4
last_tested: 10/01/2017
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Lutins
  - 
    title: La scène
  - 
    title: Faire un tambour
  - 
    title: "Défi : Améliorez votre tambour"
  - 
    title: Faire un chanteur
  - 
    title: Costumes
  - 
    title: "Défi: changez le costume de votre tambour"
  - 
    title: "Défi: faites votre propre orchestre"
