---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: In questo progetto imparerai come programmare il tuo strumento musicale!
version: 4
last_tested: 2018-10-12
steps:
  - 
    title: Introduzione
  - 
    title: Sprite
  - 
    title: Lo Stage
  - 
    title: Creare un tamburo
  - 
    title: "Sfida: perfeziona il tamburo"
    challenge: true
  - 
    title: Creare un cantante
  - 
    title: I Costumi
  - 
    title: "Sfida: Cambiare il costume del tamburo"
    challenge: true
  - 
    title: "E poi?"
