---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock grubu
description: Kendi müzik enstrümanlarınızı nasıl kodlayacağınızı öğrenin
version: 4.1.0
last_tested: 2018-10-12
steps:
  - 
    title: Giriş
  - 
    title: Kukla
  - 
    title: Sahne
  - 
    title: Davul yapma
  - 
    title: "Meydan Okuma: Davulunuzu geliştirin"
    challenge: true
  - 
    title: Şarkıcı oluşturma
  - 
    title: Kılık
  - 
    title: "Meydan Okuma: müzik grubunuzu geliştirin"
    challenge: true
  - 
    title: "Sırada ne var?"
