---
hero_image: images / kahraman-rock band-large.png
theme: kırmızı
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiz-comp-0, üretim-0, topluluk-0
title: Rock grubu
description: Kendi müzik enstrümanlarınızı nasıl kodlayacağınızı öğrenin
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: çizik
site_areas: projeler
hardware: ''
software: çizik
version: 4
last_tested: 2017/10/01
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacınız olacak?
  - 
    title: Spritelar
  - 
    title: Sahne
  - 
    title: Davul yapmak
  - 
    title: 'Zorluk: Davulunuzu geliştirin'
  - 
    title: Bir şarkıcı yapmak
  - 
    title: Kostümler
  - 
    title: 'Meydan okuma: davulun kostümünü değiştir'
  - 
    title: 'Meydan okuma: kendi grubunuzu yaratın'
