---
hero_image: images / hero-rock-band-large.png
listed: true
copyedit: false
title: Rock grubu
description: Kendi müzik enstrümanlarınızı nasıl kodlayacağınızı öğrenin
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Giriş
  - 
    title: Sprite
  - 
    title: Sahne
  - 
    title: Davul yapmak
  - 
    title: "Zorluk: Davulunuzu geliştirin"
    challenge: true
  - 
    title: Bir şarkıcı yapmak
  - 
    title: Kostümler
  - 
    title: "Meydan Okuma: müzik grubunuzu geliştirin"
    challenge: true
  - 
    title: "Sırada ne var?"
